rmf_fleet:
  name: "TwowheelBot"
  fleet_manager:
    ip: "127.0.0.1"
    port: 22011
    user: "first_user"
    password: "rnadom_password"
  limits:
    linear: [0.5, 0.75] 
    angular: [0.6, 2.0]
  profile:
    footprint: 0.3
    vicinity: 0.38
  reversible: True
  battery_system:
    voltage: 24.0
    capacity: 50.0
    charging_current: 5.0
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.3
  recharge_soc: 0.95
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "park" # [park, charge, nothing]

# List of robots
robots:
  botA:
    robot_config:
      max_delay: 15.0
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "idle_station"
        orientation: 0.0
      charger:
        waypoint: "charging_station"

  botB:
    robot_config:
      max_delay: 15.0
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "charging_station" 
        orientation: 0.0
      charger:
        waypoint: "charging_station"

  # Add robotC and robotD similarly